name = "external_name"
id = "external_id"
base_url = "https://ocp-external.oss-cn-hongkong.aliyuncs.com"
version = ["1.0.0","2.0.0"]
default_version = "2.0.0"
configuration = ["default"]
default_configuration = "default"